name: inception

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    secrets:
      - credentials
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    env_file: .env
    secrets:
      - credentials
      - db_password
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    networks:
      - inception_network

  ftp:
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    restart: unless-stopped
    secrets:
      - credentials
    depends_on:
      - wordpress
    networks:
      - inception_network
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpouillo/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mpouillo/data/wordpress

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
