name: inception

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DOMAIN_NAME: ${DOMAIN_NAME}
    secrets:
      - db_password
      - db_user
      - wp_admin_email
      - wp_admin_password
      - wp_admin_user
      - wp_email
      - wp_password
      - wp_user
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
      - static_website
    environment:
      COUNTRY: ${COUNTRY}
      STATE: ${STATE}
      LOCALITY: ${LOCALITY}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_UNIT: ${ORGANIZATION_UNIT}
      COMMON_NAME: ${COMMON_NAME}
      USER_ID: ${USER_ID}
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

  redis:
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    networks:
      - inception_network

  ftp:
    build:
      context: requirements/bonus/ftp
      dockerfile: Dockerfile
    container_name: ftp
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      COUNTRY: ${COUNTRY}
      STATE: ${STATE}
      LOCALITY: ${LOCALITY}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_UNIT: ${ORGANIZATION_UNIT}
      COMMON_NAME: ${COMMON_NAME}
      USER_ID: ${USER_ID}
    secrets:
      - ftp_password
      - ftp_user
    depends_on:
      - wordpress
    networks:
      - inception_network
    ports:
      - "20:20"
      - "21:21"
      - "40000-40005:40000-40005"
    volumes:
      - wordpress_data:/var/www/html

  static_website:
    build:
      context: requirements/bonus/static_website
      dockerfile: Dockerfile
    container_name: static_website
    restart: unless-stopped
    networks:
      - inception_network

  adminer:
    build:
      context: requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception_network
    ports:
      - "8080:8080"

  portainer:
    build:
      context: requirements/bonus/portainer
      dockerfile: Dockerfile
    container_name: portainer
    restart: unless-stopped
    secrets:
      - portainer_password
    networks:
      - inception_network
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/portainer

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/db_user.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  ftp_user:
    file: ../secrets/ftp_user.txt
  portainer_password:
    file: ../secrets/portainer_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_email:
    file: ../secrets/wp_email.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_user:
    file: ../secrets/wp_user.txt
